### ISSUE TITLE
Why some bins in the output 'scores', e.g. scores[13]， are all zeros for all 33268 samples? 

### ISSUE THREAD

**Issue by cristina510** [kyu-sz/WPAL-network#18]
Hi,  @kyu-sz
After I train and test the caffe model , I estimate the binding results. However,  I find there exists mistakes in the concat of SPP , which is called scores. For example,  the 13th column of 'scores' are all zeros in detector.pkl, which causes binding values to be NAN. Could you give me some suggestions on the possible reason? Any reply will be highly appreciated.

**Comment by kyu-sz** [comment]
I did not observe this in my own experiments. It is indeed possible that a detector gives 0 scores to all training examples after the training process, though this is not desired.
However, in this situation, the average score of positive examples ("PAve" in the paper) is also 0 (otherwise an infinite binding value also makes sense, though you can improve this by setting a upper bound of the binding value, probably dynamic to the "PAve"). Then the binding value is actually counted by 0/0. By intuition, this detector is useless at all, and it should not be bound to any attribute.
You can improve the robustness of this program by dealing with this special case, that is, if zero value is detected in "NAve", check "PAve" and set the binding value with special rules.
By the way, it is also recommended that you change your training parameters and the random seed to get a better model with all detectors meaningful.
