### ISSUE TITLE
Loss is above 64.0 when Iteration 0

### ISSUE THREAD

**Issue by shuye-cheung** [kyu-sz/WPAL-network#2]
Hi, @kyu-sz ,

when I try to recover your experiments reported in paper, I found the loss is above 64.0 when Iteration is 0. Such a big number (64.0) shocked me and I would like to ask you help me confirm if it is normal number.
Additionally,  how long will it take when training these models? And how much is the loss when converged.

Thanks. Any replies will be appreciated.

**Comment by kyu-sz** [comment]
Hi, @shuye-cheung , thank you for your interest in my work!

This is a normal initial loss, since it sums up the logistic loss of 92 attributes (for RAP dataset). It will gradually decrease, if you train the network properly.

Two days are enough for the loss to drop to around 10 or 5. It doesn't really matter, since further training does not increase test accuracy.

It will be highly appreciated if you can apply some tricks on the training of this network to make it converge to a lower loss and display higher test accuracy.
