### ISSUE TITLE
Facing problems while training on CPU based system. 

### ISSUE THREAD

**Issue by Awadhesh42** [kyu-sz/WPAL-network#20]
I am using CPU for training but it is taking too much time with original RAP database. Is there any way to trim data so that the computation speed will improve??
What changes do I need in codes to reduce the number of iterations ??
I am using pretrained GoogleNet at present for training as VGG_pretrained VGG_CNN_S model.

**Comment by Awadhesh42** [comment]
Do I need Matlab preinstalled on my system to use RAP dataset??

**Comment by kyu-sz** [comment]
It usually takes a long time to train this network even using a Titan X GPU, so I think using CPU for training is not practical. But if you insist, there is an "iters" parameter for the train_net.py. You can refer a script to see how to call train_net.py from shell.
You don't need Matlab preinstalled since there is python code in this project for reading the .mat files. However, it is highly recommended that you install the Matlab and peek into the structure of the RAP dataset, so that you can better understand the codes and reorganize other datasets in the same form as RAP and easily apply this project on them.
The only documentation for this project is [our paper](https://www.dropbox.com/s/vsmi7hjs8p6um53/0281.pdf?dl=1).

**Comment by Awadhesh42** [comment]
I am facing problem while testing the model. Can you please help me how to debug it??
My problem is under mentioned.
When I am testing my model using Googlenet I am getting this error.
IOError: [Errno 2] No such file or directory: './output/googlenet/attributes.pkl'

**Comment by kclch** [comment]
I also use the cpu to train the model, but run the script "./experiments/examples/VGG_CNN_S/train_vgg_s_rap_cpu.sh" instead of "./experiments/examples/VGG_CNN_S/train_vgg_s_rap_0.sh".
then appear the problem"./experiments/scripts/wpal_net.sh: Line 39: 19548 killed. /tools/train_net.py --gpu ${GPU_ID} --solver models/${NET}/solver.prototxt --weights $ {WEIGHTS} --db ${DB} --setid ${DB_SET} --outputdir data/snapshots/${NET}/${DB_SET} --iters ${ITERS} ${EXTRA_ARGS}" This is due to computer configuration Question?
