### ISSUE TITLE
how to inference your WPAL-Network by using own data

### ISSUE THREAD

**Issue by jhj7905** [kyu-sz/WPAL-network#9]
hello.

I did finished the process in Usage part like below 
- ./data/scripts/fetch_pretrained_vgg_cnn_s_model.sh
- ./experiments/example/VGG_CNN_S/train_vgg_s_rap_0.sh
- ./experiments/examples/VGG_CNN_S/test_vgg_s_rap.sh

Could you tell me how to inference your Network by using my own data?

**Comment by kyu-sz** [comment]
You can mimic the [RAP dataset class](https://github.com/kyu-sz/WPAL-network/blob/master/lib/utils/rap_db.py) to implement a new class in order to feed your own data into the network.
Sorry for the rough code. There aren't clear definition of interfaces that you must implement. Try your best to have as many same members as the rap_db class in your own class as possible. To determine whether one is necessary, just run the code without it and see if it could raise some errors.
